#!/bin/bash
# garimmit V1
# Create message with proper reference to rep issue based on branch name ddd_issueName
# Then add all changes in unstaged and commit with the respective message
# Authors: Vinicius Saturnino & Mateus Gomes

if [ ! -z "$1" -a "$1" != " " ]; then
   bold=$(tput bold)
   normal=$(tput sgr0)

   declare number
   number=$(git branch | grep '*' | grep -o -E '[0-9]+') 

   if [[ $number =~ ^[0-9]+$ ]]; then
      number=$number
   else
      echo -e "${bold}@@@@@@@@@@@@@@@@@@@@@@@@@@@ W A R N I N G @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@${normal}"  
      echo -e "\nYou're out of a issue branch, the only way of contibuiting to Garimpei! :X "
      echo -e "\nAre you ${bold}absolutely${normal} certain to try to commit in ${bold}$(git branch | grep '*' | sed 's|[*]||g')${normal} ? (it wont pass ${bold}the CI${normal} on Github)\n"

      read -p "(${bold}y/n${normal}) " flag

      if [ $flag == "n" ]; then
         exit 1
      fi

      echo ""
      read -p "What's the ${bold}issue number${normal}? " number
      echo ""
   fi

   declare flag="y"
   declare commit_type=""

   while [ $flag == 'y' ]; do
      echo -e "What's the type of your commit?\n"
      echo -e "   ${bold}feat${normal} (A new feature)\n
   ${bold}fix${normal} (A bug Fix)\n
   ${bold}docs${normal} (Documentation only changes)\n
   ${bold}style${normal} (Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))\n
   ${bold}refactor${normal} (A code change that neither fixes a bug nor adds a feature)\n
   ${bold}perf${normal} (A code change that improves performance)\n
   ${bold}test${normal} (Adding missing tests or correcting existing tests)\n
   ${bold}build${normal} (Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm))\n
   ${bold}ci${normal} (Changes to our CI configuration files and s (example scopes: Travis, Circle, BrowserStack, SauceLabs))\n
   ${bold}chore${normal} (Other changes that don't modify src or test files)\n
   ${bold}revert${normal} (Reverts a previous commit)\n"

      read commit_type
      echo ""

      if [[ "${commit_type}" =~ feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert ]]; then
         flag="n"
      else
         echo -e "Wrong type.. try again!\n\n"
      fi
   done

   message="$commit_type: UnBArqDsw2021-2/2021.2_G5_Garimpei#$number $1"

   echo ""
   read -p "Are you ${bold}pairing${normal}? (${bold}y/n${normal}) " pairing
   echo ""

   if [ $pairing == "y" ]; then

      declare -A map

      map["db"]="Daniel Barcelos <danielbarcelos.7@hotmail.com>"
      map["dr"]="Denys Rogeres <dennysrogeres@gmail.com>"
      map["ju"]="Juliana Valle <juju.pvg@gmail.com>"
      map["mat"]="Mateus Gomes <mateusgomes.nascimento21@gmail.com>"
      map["af"]="Matheus Afonso <matheusafonsouza@gmail.com>"
      map["pv"]="Paulo Victor <paulovmel@gmail.com>"
      map["tm"]="Thiago Mesquita <thiago099carvalho@gmail.com>"
      map["vg"]="Victor Gonçalves <victor.eng.unb@gmail.com>"
      map["vs"]="Vinicius Saturnino <viniciussaturnino78@gmail.com>"

      declare flag="y"

      message+="\n\n"

      while [ $flag == 'y' ]; do
         echo -e "With who?\n"
         echo -e "
   (${bold}db${normal})Daniel\n
   (${bold}dr${normal})Denys\n
   (${bold}ju${normal})Juliana\n
   (${bold}mat${normal})Matola\n
   (${bold}af${normal})Afonso\n
   (${bold}pv${normal})Paulo\n
   (${bold}tm${normal})Thiago\n
   (${bold}vg${normal})Victor\n
   (${bold}vs${normal})Vinicius"

         read pairing_name

         echo ""

         if [[ "${pairing_name}" =~ db|dr|ju|mat|af|pv|tm|vg|vs ]]; then
            message+="\nCo-authored-by: ${map[${pairing_name}]}"

            read -p "Anyone else? (${bold}y/n${normal}) " flag
            echo ""
         else
            echo -e "Wrong acronym.. try again!\n\n"
         fi
      done

   fi

   echo -e "That's the correct message ?\n\n\n$message\n\n"
   read -p "(${bold}y/n${normal}): " flag

   if [ $flag != 'n' ]; then
      echo ""

      echo -e "What do you want do stage?\n
   (${bold}e${normal})verything\n
   (${bold}s${normal})omethings\n
   (${bold}n${normal})othing"
      read flag

      echo ""

      if [ $flag == 'e' ]; then
         git add .
      else 
         if [ $flag == 's' ]; then
            echo -e "Let's ${bold}stage${normal} the changes!\n\n"
            git add -i

            echo ""
         fi
      fi

      git commit -m"$(echo -e $message)"
      echo -e "\n\n"
      echo -e "${bold}Everything commited!! ;)"
   else
      echo -e "\n\n"
      echo "${bold}Run me again! :("
   fi
else
   echo -e "Wheres the message?! Run me again"
fi
