site_name: Garimpei

repo_name: "2021.2-Garimpei"
repo_url: "https://github.com/UnBArqDsw2021-2/2021.2_G5_Garimpei"

theme:
  name: material
  language: "pt"
  logo: "assets/favicon.ico"
  favicon: "assets/favicon.ico"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Planejamento:
      - Metodologia: content/planejamento/metodologia.md
  - Pré Rastreabilidade:
      - Mapa Mental: content/pre_rastreabilidade/mapa_mental.md
  - Elicitação:
      - Questionário: content/elicitacao/questionario.md
      - Brainstorming: content/elicitacao/brainstorming.md
      - Personas: content/elicitacao/personas.md
  - Validação:
      - Protótipo de baixa fidelidade: content/validacao/prototipos/prototipo_baixa_fidelidade.md
  - Modelagem:
      - Priorização: content/modelagem/priorizacao.md
dev_addr: "0.0.0.0:8000"
