site_name: Garimpei

repo_name: "2021.2-Garimpei"
repo_url: "https://github.com/UnBArqDsw2021-2/2021.2_G5_Garimpei"

theme:
  name: material
  language: "pt"
  logo: "global/assets/favicon.ico"
  favicon: "global/assets/favicon.ico"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Desenho de Software (Base):
      - Projeto não orientado a abordagens específicas:
          - Design Sprint: entrega_I/projeto_nao_orientado_a_abordagens_especificas/design_sprint.md
          - Rich Picture: entrega_I/projeto_nao_orientado_a_abordagens_especificas/rich_picture.md
          - 5W2H: entrega_I/projeto_nao_orientado_a_abordagens_especificas/5w2h.md
          - Diagrama Causa e Efeito: entrega_I/projeto_nao_orientado_a_abordagens_especificas/diagrama_causa_efeito.md
          - Plano de Riscos: entrega_I/projeto_nao_orientado_a_abordagens_especificas/plano_riscos.md
          - Mapa Mental: entrega_I/projeto_nao_orientado_a_abordagens_especificas/mapa_mental.md
          - Protótipo de Baixa Fidelidade: entrega_I/projeto_nao_orientado_a_abordagens_especificas/prototipo_baixa_fidelidade.md
          - Protótipo de Média Fidelidade: entrega_I/projeto_nao_orientado_a_abordagens_especificas/prototipo_media_fidelidade.md
          - Protótipo de Alta Fidelidade: entrega_I/projeto_nao_orientado_a_abordagens_especificas/prototipo_alta_fidelidade.md
          - Elicitação:
              - Questionário: entrega_I/projeto_nao_orientado_a_abordagens_especificas/elicitacao/questionario.md
              - Brainstorming: entrega_I/projeto_nao_orientado_a_abordagens_especificas/elicitacao/brainstorming.md
              - Introspecção: entrega_I/projeto_nao_orientado_a_abordagens_especificas/elicitacao/introspeccao.md
              - Resultados: entrega_I/projeto_nao_orientado_a_abordagens_especificas/elicitacao/resultado.md
          - Backlog: entrega_I/projeto_nao_orientado_a_abordagens_especificas/backlog.md
          - Priorização: entrega_I/projeto_nao_orientado_a_abordagens_especificas/priorizacao.md
      - Processos, metodologias e abordagens:
          - Metodologia: entrega_I/processos_metodologias_e_abordagens/metodologia.md
          - BPMN: entrega_I/processos_metodologias_e_abordagens/modelagem_bpmn.md
      - Iniciativas extras:
          - Personas: entrega_I/extras/personas.md
          - Manual de Identidade Visual: entrega_I/extras/identidade_visual.md
          - Guia de Contribuição: entrega_I/extras/contribuicao.md
      - Atas:
          - Ata da reunião 27/01: entrega_I/atas/ata_2701.md
          - Ata da reunião 28/01: entrega_I/atas/ata_2801.md
  - Desenho de Software (Modelagem):
      - Notação UML - Diagramas Estáticos:
          - Diagrama de Classes: entrega_II/diagramas_estaticos/diagrama_de_classes.md
          - Diagrama de Pacotes: entrega_II/diagramas_estaticos/diagrama-de-pacotes.md
          - Diagrama de Componentes: entrega_II/diagramas_estaticos/diagrama-de-componentes.md
      - Notação UML - Diagramas Dinâmicos:
          - Diagrama de Atividades: entrega_II/diagramas_dinamicos/diagrama-de-atividades.md
          - Diagrama de Estados: entrega_II/diagramas_dinamicos/diagrama-de-estados.md
          - Diagrama de Sequência: entrega_II/diagramas_dinamicos/diagrama_de_sequencia.md
          - Diagrama de Comunicação: entrega_II/diagramas_dinamicos/diagrama_de_comunicacao.md
      - Modelagem Ágil:
          - Backlog: entrega_II/modelagem_agil/backlog.md
      - Iniciativas extras:
          - Reorganização da Documentação: entrega_II/extras/docs_refactor.md
          - Melhoria do Protótipo de Alta Fidelidade: entrega_II/extras/prototipo_alta_fidelidade.md
          - Atas:
              - 09/02 - Reunião de Planning: entrega_II/extras/atas/ata_0902.md
              - 17/02 - Reunião de Feedback: entrega_II/extras/atas/ata_1702.md
  - Desenho de Software (Padrões de Projeto):
      - GRASPs: entrega_III/grasps/index.md
      - GoFs:
          - Criacionais:
              - Singleton: entrega_III/gofs/criacionais/singleton.md
              - Multiton: entrega_III/gofs/criacionais/multiton.md
          - Comportamentais:
              - State: entrega_III/gofs/comportamentais/state.md
              - Iterator: entrega_III/gofs/comportamentais/iterator.md
              - Chain Of Responsibility: entrega_III/gofs/comportamentais/chain_of_responsibility.md
          - Estruturais:
              - Decorator: entrega_III/gofs/estruturais/decorator.md
              - Composite: entrega_III/gofs/estruturais/composite.md
              - Facade: entrega_III/gofs/estruturais/facade.md
      - Iniciativas extras:
          - Padrões Emergentes: entrega_III/extras/padroes_emergentes.md
          - Guia de Contribuição: entrega_III/extras/contribuicao.md
          - Dojos: entrega_III/extras/dojos.md
          - Protótipo de Alta Fidelidade: entrega_III/extras/evolucao_prototipo.md
  - Apresentações: apresentacoes/index.md
dev_addr: "0.0.0.0:8000"
