site_name: Garimpei

repo_name: "2021.2-Garimpei"
repo_url: "https://github.com/UnBArqDsw2021-2/2021.2_G5_Garimpei"

theme:
  name: material
  language: "pt"
  logo: "assets/favicon.ico"
  favicon: "assets/favicon.ico"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Desenho de Software (Base):
      - Projeto não orientado a abordagens específicas:
          - Design Sprint: content/design_sprint.md
          - Rich Picture: content/pre_rastreabilidade/rich_picture.md
          - 5W2H: content/pre_rastreabilidade/5w2h.md
          - Diagrama Causa e Efeito: content/pre_rastreabilidade/diagrama_causa_efeito.md
          - Plano de Riscos: index.md
          - Mapa Mental: content/pre_rastreabilidade/mapa_mental.md
          - Protótipo de Baixa Fidelidade: content/produto/prototipo_baixa_fidelidade.md
          - Protótipo de Média Fidelidade: content/produto/prototipo_media_fidelidade.md
          - Protótipo de Alta Fidelidade: content/produto/prototipo_alta_fidelidade.md
          - Elicitação:
              - Questionário: content/elicitacao/questionario.md
              - Brainstorming: content/elicitacao/brainstorming.md
              - Introspecção: content/elicitacao/introspeccao.md
              - Resultados: content/elicitacao/resultado.md
          - Backlog: content/modelagem/backlog.md
          - Priorização: content/modelagem/priorizacao.md
      - Processos, metodologias e abordagens:
          - Metodologia: content/planejamento/metodologia.md
          - BPMN: index.md
      - Iniciativas extras:
          - Personas: content/elicitacao/personas.md
          - Manual de Identidade Visual: content/produto/identidade_visual.md
          - Guia de Contribuição: content/extras/contribuicao.md
          - Validação:
              - Protótipo de baixa fidelidade: content/validacao/prototipos/prototipo_baixa_fidelidade.md
      - Atas:
          - Ata da reunião 27/01: content/extras/atas/ata_2701.md
          - Ata da reunião 28/01: content/extras/atas/ata_2801.md
  - Apresentações: index.md
dev_addr: "0.0.0.0:8000"
